### ISSUE TITLE
Continuously showing "Something Went Wrong" While Adding a Source

### ISSUE THREAD

**Issue by RoManInv** [4gray/iptvnator#482]
**Describe the bug**
While attempting to add an IPTV m3u source, the frontend continuously reports "something went wrong". 

**To Reproduce**
1. Access the frontend from LAN with http://my.iptvnator.ip:43080
2. Click the "+" button from the main page and add a verified m3u source obtained from GitHub
3. At the bottom of the page, it shows "something went wrong"
4. Repeat 1-3, add other verified m3u/m3u8 sources (all obtained from GitHub), the same error message appears

**Expected behavior**
The source should be added.

**Desktop (please complete the following information):**
**This does not apply to me. I'm using Dockage. Below is the docker-compose commands**
- Dockage: using host network, here both hostname `my.dockage.ip` and `my.iptvnator.ip` refer to the correct LAN-IP address of Dockage. 
- Using the following Docker-compose script to deploy the backend and the frontend
```
services:
  iptvnator-backend:
    image: 4gray/iptvnator-backend:latest
    ports:
      - 43000:3000
    environment:
      - CLIENT_URL=http://my.iptvnator.ip:43080#this one should match with the
        address and port in frontend CLIENT_URL env
  iptvnator-frontend:
    image: 4gray/iptvnator:latest
    ports:
      - 43080:80
    environment:
      - BACKEND_URL=http://my.iptvnator.ip:3000 # this one should match with the address of the backend service
networks: {}
```

**Additional context**
There might be another bug for indicating the backend URL for iptvnator frontend. According to your documentation, the expected line for backend URL should be:
`- BACKEND_URL=http://my.iptvnator.ip:43000`
However, when deployed using the expected line, the frontend will report "backend not reachable" when following the Step 1-3 of Bug Reproduction. By changing the port to 3000, the frontend shows the problem as described above. Below is the additional information of what the browser shows when accessing port 3000 and 43000 using HTTP:
- http://my.iptvnator.ip:3000
`{"status":"OK","version":{"major":2,"minor":12,"revision":1}}`
- http://my.iptvnator.ip:3000
`Hello World`

**Comment by 4gray** [comment]
It your case the BACKEND_URL should point to the exposed port:
`- BACKEND_URL=http://my.iptvnator.ip:43000`
Also make sure that there is a space between comment and port at line 7.

```
services:
  iptvnator-backend:
    image: 4gray/iptvnator-backend:latest
    ports:
      - 43000:3000
    environment:
      - CLIENT_URL=http://localhost:43080
  iptvnator-frontend:
    image: 4gray/iptvnator:latest
    ports:
      - 43080:80
    environment:
      - BACKEND_URL=http://localhost:43000
networks: {}
```

**Comment by 4gray** [comment]
![CleanShot 2024-11-30 at 18 03 32@2x](https://github.com/user-attachments/assets/e1ab89e9-a4c2-41d0-b3cc-aabda65d057a)

I tested your config just now, works on my machine. Try to open browser dev tools and in the network tab make sure that the correct ip:port address is used for the `/parse` request.

**Comment by RoManInv** [comment]
Thank you for testing my config and the detailed example in the figure. I have done the following steps and got the result from chrome dev tool as shown in the picture below
Steps:
1. Open http://192.168.1.220:43080 in the browser, and activate dev tool
2. Add playlist by URL
3. Enter a verified m3u playlist
4. "Something went wrong" appears
Result of dev tool:
![image](https://github.com/user-attachments/assets/504bfec8-ef77-4b8c-815a-8b95c5fa7e23)

As I'm running iptvnator (both back- and frontend) on a stand alone mini server, I replaced the localhost with the exact LAN IP address, resulting in the following config:
```
services:
  iptvnator-backend:
    image: 4gray/iptvnator-backend:latest
    ports:
      - 43000:3000
    environment:
      - CLIENT_URL=http://192.168.1.220:43080
  iptvnator-frontend:
    image: 4gray/iptvnator:latest
    ports:
      - 43080:80
    environment:
      - BACKEND_URL=http://192.168.1.220:43000
networks: {}
```
Then I performed exactly the same steps as described above, and the dev tool gave me the following result:
![image](https://github.com/user-attachments/assets/a0bb1375-8d37-4673-9eb0-cf106a343e44)
This time, the client returned "backend not reachable". 
In addition, I have also checked all the processes on my VM with IP 192.168.1.220. The result shows that the port 43000 or 43080 are not taken by any apps/containers other than iptvnator. 
PS: I did not collapse the response header, the dev tool has not received any response for this request.
